name: Hello world workflows

on:
  push:
    branches:
      - main
  pull:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goodbye
        run: echo "Good bye"
        shell: bash
